# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprout < Formula
  desc "The Ultimate Custom Spring Initializer CLI"
  homepage "https://github.com/jessn-dev/sprout"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jessn-dev/sprout/releases/download/v0.1.0/sprout_0.1.0_darwin_amd64.tar.gz"
      sha256 "e33bb4643ccf5e49360d19b352e39fb8915e86cc4cf05a6b5bfc3602d173072a"

      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jessn-dev/sprout/releases/download/v0.1.0/sprout_0.1.0_darwin_arm64.tar.gz"
      sha256 "4b7f748f5d2d41b0752118b5f573492ffe9bd42bcb9ff39d007dae4856bf1888"

      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessn-dev/sprout/releases/download/v0.1.0/sprout_0.1.0_linux_amd64.tar.gz"
      sha256 "74738ed971377c4ae5f5da5b9870545bb21e420b883a31419d07b01df2e533bf"
      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessn-dev/sprout/releases/download/v0.1.0/sprout_0.1.0_linux_arm64.tar.gz"
      sha256 "44c27f20cb677d641aba18b2fd9e7b086b82ccd32a0d46494b53dd4db09ba47f"
      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  test do
    system "#{bin}/sprout --version"
  end
end
