# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprout < Formula
  desc "The Ultimate Custom Spring Initializer CLI"
  homepage "https://github.com/jessn-dev/sprout"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jessn-dev/sprout/releases/download/v0.1.1/sprout_0.1.1_darwin_amd64.tar.gz"
      sha256 "43e536b710e69325d0f511bf1080878fbab6d5adc3e3df60ff31f68c1b134065"

      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jessn-dev/sprout/releases/download/v0.1.1/sprout_0.1.1_darwin_arm64.tar.gz"
      sha256 "41b4b9181606c2c372a1f3c51963e11aecb0b4847a6c053422fc6ca95129efcd"

      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessn-dev/sprout/releases/download/v0.1.1/sprout_0.1.1_linux_amd64.tar.gz"
      sha256 "3579504a415d6c12ebe87c5a8fc2b6518b643be5b9823e640f62919b233144b9"
      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessn-dev/sprout/releases/download/v0.1.1/sprout_0.1.1_linux_arm64.tar.gz"
      sha256 "788ce360f793830ed0ed70833ce1c28fa5319a5a80a2fdf86fd81e9284eaeec6"
      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  test do
    system "#{bin}/sprout --version"
  end
end
