# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprout < Formula
  desc "The Ultimate Custom Spring Initializer CLI"
  homepage "https://github.com/jessn-dev/sprout"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jessn-dev/sprout/releases/download/v1.0.0/sprout_1.0.0_darwin_amd64.tar.gz"
      sha256 "18a2a1df1683fef2821aa60e7e23f5f1268c996801f3112b4c0ca4f59d8ace32"

      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jessn-dev/sprout/releases/download/v1.0.0/sprout_1.0.0_darwin_arm64.tar.gz"
      sha256 "26c268d0fc5a83bd87e73b5bcedc9ab98cd83485bb0b601c1ce04d9a4d3ed5ce"

      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessn-dev/sprout/releases/download/v1.0.0/sprout_1.0.0_linux_amd64.tar.gz"
      sha256 "206033bd24a4a1f553534062b4dbbab053f4769e08662f5800f152e7e207d46a"
      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessn-dev/sprout/releases/download/v1.0.0/sprout_1.0.0_linux_arm64.tar.gz"
      sha256 "e4d5cf27ec0da12968f8fef436357548368589a98b2e0bafa5a6a0eed474164e"
      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  test do
    system "#{bin}/sprout --version"
  end
end
