# This file was generated by GoReleaser. DO NOT EDIT.
cask "nock" do
  version "0.1.0-rc1"

  on_macos do
    on_intel do
      sha256 "e58951ca7e66181e620fe2bc2429e1d166fddbc0038943cfdabfc2bab61e7d3d"
      url "https://github.com/jessn-dev/nock/releases/download/v#{version}/nock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "99aac8a60c570c4bc858bf242ece4eb7611964c2d8179de157d807bd0b4a3614"
      url "https://github.com/jessn-dev/nock/releases/download/v#{version}/nock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2693d220a9ca392e4ef0c61b9600155236188a535946edf31d69fd492b865c57"
      url "https://github.com/jessn-dev/nock/releases/download/v#{version}/nock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7df266e4a4491af337530cf563287e884770791cab5c1d1f42ecee96d68550c7"
      url "https://github.com/jessn-dev/nock/releases/download/v#{version}/nock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nock"
  desc "AI-aware command launcher for pentesters and operators"
  homepage "https://github.com/jessn-dev/nock"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nock"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nock"]
    end
  end

  # No zap stanza required

end
